# Generated by Django 4.1.7 on 2023-03-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_ids_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ids',
            name='status',
            field=models.CharField(default='Foydalanilmagan', max_length=200, null=True),
        ),
    ]
